export interface Profesor {
    id?: number,
    nombre: string,
    apellidos: string,
    username: string,
    email: string,
    password?: string,
    telefono: string,
    direccion: string,
    ciudad: string,
    latitud: number,
    longitud: number,
    imagen: string,
    edad: number,
    fecha_nacimiento: string,
    genero: string,
    dni: string,
    fecha_alta: string,
    rol: string,
    borrado: boolean,
    experiencia: number,
    precio: number,
    asignaturas: []
}